//
//Copyright The containerd Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: services/blockcache/v1/blockcache.proto

package blockcache

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FillMessage is the single message type on both sides of the Fill stream.
type FillMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*FillMessage_Hello
	//	*FillMessage_Fill
	//	*FillMessage_Filled
	//	*FillMessage_Error
	Msg isFillMessage_Msg `protobuf_oneof:"msg"`
}

func (x *FillMessage) Reset() {
	*x = FillMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_blockcache_v1_blockcache_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FillMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillMessage) ProtoMessage() {}

func (x *FillMessage) ProtoReflect() protoreflect.Message {
	mi := &file_services_blockcache_v1_blockcache_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillMessage.ProtoReflect.Descriptor instead.
func (*FillMessage) Descriptor() ([]byte, []int) {
	return file_services_blockcache_v1_blockcache_proto_rawDescGZIP(), []int{0}
}

func (m *FillMessage) GetMsg() isFillMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *FillMessage) GetHello() *Hello {
	if x, ok := x.GetMsg().(*FillMessage_Hello); ok {
		return x.Hello
	}
	return nil
}

func (x *FillMessage) GetFill() *FillRequest {
	if x, ok := x.GetMsg().(*FillMessage_Fill); ok {
		return x.Fill
	}
	return nil
}

func (x *FillMessage) GetFilled() *Filled {
	if x, ok := x.GetMsg().(*FillMessage_Filled); ok {
		return x.Filled
	}
	return nil
}

func (x *FillMessage) GetError() *FillError {
	if x, ok := x.GetMsg().(*FillMessage_Error); ok {
		return x.Error
	}
	return nil
}

type isFillMessage_Msg interface {
	isFillMessage_Msg()
}

type FillMessage_Hello struct {
	// Hello: first message from shim → daemon.  Identifies the block.
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type FillMessage_Fill struct {
	// Fill: shim → daemon.  Request that [offset, offset+length) be filled.
	Fill *FillRequest `protobuf:"bytes,2,opt,name=fill,proto3,oneof"`
}

type FillMessage_Filled struct {
	// Filled: daemon → shim.  Ranges that are now resident in the backing file.
	Filled *Filled `protobuf:"bytes,3,opt,name=filled,proto3,oneof"`
}

type FillMessage_Error struct {
	// Error: daemon → shim.  A fill could not be completed; the shim should
	// propagate an error to the waiting container read.
	Error *FillError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*FillMessage_Hello) isFillMessage_Msg() {}

func (*FillMessage_Fill) isFillMessage_Msg() {}

func (*FillMessage_Filled) isFillMessage_Msg() {}

func (*FillMessage_Error) isFillMessage_Msg() {}

// Hello identifies the block to fill.  Must be the first message on the stream.
type Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// blockid is an opaque identifier for the block, typically a content digest
	// (e.g. "sha256:abc…") matching the blockid= option on the mount descriptor.
	Blockid string `protobuf:"bytes,1,opt,name=blockid,proto3" json:"blockid,omitempty"`
}

func (x *Hello) Reset() {
	*x = Hello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_blockcache_v1_blockcache_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_services_blockcache_v1_blockcache_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_services_blockcache_v1_blockcache_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetBlockid() string {
	if x != nil {
		return x.Blockid
	}
	return ""
}

// FillRequest asks the daemon to ensure [offset, offset+length) is resident.
// The daemon will call EnsureRange on the cache and respond with Filled.
type FillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Length int64 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *FillRequest) Reset() {
	*x = FillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_blockcache_v1_blockcache_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillRequest) ProtoMessage() {}

func (x *FillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_blockcache_v1_blockcache_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillRequest.ProtoReflect.Descriptor instead.
func (*FillRequest) Descriptor() ([]byte, []int) {
	return file_services_blockcache_v1_blockcache_proto_rawDescGZIP(), []int{2}
}

func (x *FillRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FillRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

// Filled reports which byte ranges are now resident in the backing file.
// Ranges are chunk-aligned and may extend beyond the requested range.
// They are cumulative — the shim should OR them into its local bitmap.
// A single Filled message may satisfy multiple pending FillRequests.
type Filled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ranges []*ByteRange `protobuf:"bytes,1,rep,name=ranges,proto3" json:"ranges,omitempty"`
}

func (x *Filled) Reset() {
	*x = Filled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_blockcache_v1_blockcache_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filled) ProtoMessage() {}

func (x *Filled) ProtoReflect() protoreflect.Message {
	mi := &file_services_blockcache_v1_blockcache_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filled.ProtoReflect.Descriptor instead.
func (*Filled) Descriptor() ([]byte, []int) {
	return file_services_blockcache_v1_blockcache_proto_rawDescGZIP(), []int{3}
}

func (x *Filled) GetRanges() []*ByteRange {
	if x != nil {
		return x.Ranges
	}
	return nil
}

// FillError signals that a fill request failed.  The shim should propagate
// an I/O error to the container rather than retrying indefinitely.
type FillError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *FillError) Reset() {
	*x = FillError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_blockcache_v1_blockcache_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FillError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillError) ProtoMessage() {}

func (x *FillError) ProtoReflect() protoreflect.Message {
	mi := &file_services_blockcache_v1_blockcache_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillError.ProtoReflect.Descriptor instead.
func (*FillError) Descriptor() ([]byte, []int) {
	return file_services_blockcache_v1_blockcache_proto_rawDescGZIP(), []int{4}
}

func (x *FillError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ByteRange is a [offset, offset+length) byte span.
type ByteRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Length int64 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *ByteRange) Reset() {
	*x = ByteRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_blockcache_v1_blockcache_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ByteRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByteRange) ProtoMessage() {}

func (x *ByteRange) ProtoReflect() protoreflect.Message {
	mi := &file_services_blockcache_v1_blockcache_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByteRange.ProtoReflect.Descriptor instead.
func (*ByteRange) Descriptor() ([]byte, []int) {
	return file_services_blockcache_v1_blockcache_proto_rawDescGZIP(), []int{5}
}

func (x *ByteRange) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ByteRange) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

var File_services_blockcache_v1_blockcache_proto protoreflect.FileDescriptor

var file_services_blockcache_v1_blockcache_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x21, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x22, 0xa7, 0x02, 0x0a,
	0x0b, 0x46, 0x69, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x40, 0x0a, 0x05,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x44,
	0x0a, 0x04, 0x66, 0x69, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x46, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04,
	0x66, 0x69, 0x6c, 0x6c, 0x12, 0x43, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x48,
	0x00, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x44, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c,
	0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42,
	0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x21, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12,
	0x18, 0x0a, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x0b, 0x46, 0x69, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x4e, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x6c,
	0x65, 0x64, 0x12, 0x44, 0x0a, 0x06, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x06, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x22, 0x25, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x6c,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x3b, 0x0a, 0x09, 0x42, 0x79, 0x74, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x32, 0x78, 0x0a, 0x0a,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x6a, 0x0a, 0x04, 0x46, 0x69,
	0x6c, 0x6c, 0x12, 0x2e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x1a, 0x2e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2f,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x61, 0x63, 0x68, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_blockcache_v1_blockcache_proto_rawDescOnce sync.Once
	file_services_blockcache_v1_blockcache_proto_rawDescData = file_services_blockcache_v1_blockcache_proto_rawDesc
)

func file_services_blockcache_v1_blockcache_proto_rawDescGZIP() []byte {
	file_services_blockcache_v1_blockcache_proto_rawDescOnce.Do(func() {
		file_services_blockcache_v1_blockcache_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_blockcache_v1_blockcache_proto_rawDescData)
	})
	return file_services_blockcache_v1_blockcache_proto_rawDescData
}

var file_services_blockcache_v1_blockcache_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_services_blockcache_v1_blockcache_proto_goTypes = []interface{}{
	(*FillMessage)(nil), // 0: containerd.services.blockcache.v1.FillMessage
	(*Hello)(nil),       // 1: containerd.services.blockcache.v1.Hello
	(*FillRequest)(nil), // 2: containerd.services.blockcache.v1.FillRequest
	(*Filled)(nil),      // 3: containerd.services.blockcache.v1.Filled
	(*FillError)(nil),   // 4: containerd.services.blockcache.v1.FillError
	(*ByteRange)(nil),   // 5: containerd.services.blockcache.v1.ByteRange
}
var file_services_blockcache_v1_blockcache_proto_depIdxs = []int32{
	1, // 0: containerd.services.blockcache.v1.FillMessage.hello:type_name -> containerd.services.blockcache.v1.Hello
	2, // 1: containerd.services.blockcache.v1.FillMessage.fill:type_name -> containerd.services.blockcache.v1.FillRequest
	3, // 2: containerd.services.blockcache.v1.FillMessage.filled:type_name -> containerd.services.blockcache.v1.Filled
	4, // 3: containerd.services.blockcache.v1.FillMessage.error:type_name -> containerd.services.blockcache.v1.FillError
	5, // 4: containerd.services.blockcache.v1.Filled.ranges:type_name -> containerd.services.blockcache.v1.ByteRange
	0, // 5: containerd.services.blockcache.v1.BlockCache.Fill:input_type -> containerd.services.blockcache.v1.FillMessage
	0, // 6: containerd.services.blockcache.v1.BlockCache.Fill:output_type -> containerd.services.blockcache.v1.FillMessage
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_services_blockcache_v1_blockcache_proto_init() }
func file_services_blockcache_v1_blockcache_proto_init() {
	if File_services_blockcache_v1_blockcache_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_blockcache_v1_blockcache_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FillMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_blockcache_v1_blockcache_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_blockcache_v1_blockcache_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_blockcache_v1_blockcache_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_blockcache_v1_blockcache_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FillError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_blockcache_v1_blockcache_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ByteRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_services_blockcache_v1_blockcache_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*FillMessage_Hello)(nil),
		(*FillMessage_Fill)(nil),
		(*FillMessage_Filled)(nil),
		(*FillMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_blockcache_v1_blockcache_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_blockcache_v1_blockcache_proto_goTypes,
		DependencyIndexes: file_services_blockcache_v1_blockcache_proto_depIdxs,
		MessageInfos:      file_services_blockcache_v1_blockcache_proto_msgTypes,
	}.Build()
	File_services_blockcache_v1_blockcache_proto = out.File
	file_services_blockcache_v1_blockcache_proto_rawDesc = nil
	file_services_blockcache_v1_blockcache_proto_goTypes = nil
	file_services_blockcache_v1_blockcache_proto_depIdxs = nil
}
