//go:build !no_grpc

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: services/blockcache/v1/blockcache.proto

package blockcache

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BlockCacheClient is the client API for BlockCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockCacheClient interface {
	// Fill is a long-lived bidirectional stream.
	//
	//	Shim → daemon: Hello{blockid} once, then Fill{range} messages.
	//	Daemon → shim: Filled{ranges} messages (not necessarily 1:1 with Fill).
	//
	// The shim tracks which pages are resident using its own page-level bitmap
	// and uses the Filled ranges to set bits.  When all pages are resident the
	// stream may be closed.
	//
	// Filled messages may arrive spontaneously (e.g., background prefetch)
	// or in response to a Fill request.  The daemon may coalesce multiple Fill
	// requests into a single Filled response.
	Fill(ctx context.Context, opts ...grpc.CallOption) (BlockCache_FillClient, error)
}

type blockCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockCacheClient(cc grpc.ClientConnInterface) BlockCacheClient {
	return &blockCacheClient{cc}
}

func (c *blockCacheClient) Fill(ctx context.Context, opts ...grpc.CallOption) (BlockCache_FillClient, error) {
	stream, err := c.cc.NewStream(ctx, &BlockCache_ServiceDesc.Streams[0], "/containerd.services.blockcache.v1.BlockCache/Fill", opts...)
	if err != nil {
		return nil, err
	}
	x := &blockCacheFillClient{stream}
	return x, nil
}

type BlockCache_FillClient interface {
	Send(*FillMessage) error
	Recv() (*FillMessage, error)
	grpc.ClientStream
}

type blockCacheFillClient struct {
	grpc.ClientStream
}

func (x *blockCacheFillClient) Send(m *FillMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *blockCacheFillClient) Recv() (*FillMessage, error) {
	m := new(FillMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BlockCacheServer is the server API for BlockCache service.
// All implementations must embed UnimplementedBlockCacheServer
// for forward compatibility
type BlockCacheServer interface {
	// Fill is a long-lived bidirectional stream.
	//
	//	Shim → daemon: Hello{blockid} once, then Fill{range} messages.
	//	Daemon → shim: Filled{ranges} messages (not necessarily 1:1 with Fill).
	//
	// The shim tracks which pages are resident using its own page-level bitmap
	// and uses the Filled ranges to set bits.  When all pages are resident the
	// stream may be closed.
	//
	// Filled messages may arrive spontaneously (e.g., background prefetch)
	// or in response to a Fill request.  The daemon may coalesce multiple Fill
	// requests into a single Filled response.
	Fill(BlockCache_FillServer) error
	mustEmbedUnimplementedBlockCacheServer()
}

// UnimplementedBlockCacheServer must be embedded to have forward compatible implementations.
type UnimplementedBlockCacheServer struct {
}

func (UnimplementedBlockCacheServer) Fill(BlockCache_FillServer) error {
	return status.Errorf(codes.Unimplemented, "method Fill not implemented")
}
func (UnimplementedBlockCacheServer) mustEmbedUnimplementedBlockCacheServer() {}

// UnsafeBlockCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockCacheServer will
// result in compilation errors.
type UnsafeBlockCacheServer interface {
	mustEmbedUnimplementedBlockCacheServer()
}

func RegisterBlockCacheServer(s grpc.ServiceRegistrar, srv BlockCacheServer) {
	s.RegisterService(&BlockCache_ServiceDesc, srv)
}

func _BlockCache_Fill_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BlockCacheServer).Fill(&blockCacheFillServer{stream})
}

type BlockCache_FillServer interface {
	Send(*FillMessage) error
	Recv() (*FillMessage, error)
	grpc.ServerStream
}

type blockCacheFillServer struct {
	grpc.ServerStream
}

func (x *blockCacheFillServer) Send(m *FillMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *blockCacheFillServer) Recv() (*FillMessage, error) {
	m := new(FillMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BlockCache_ServiceDesc is the grpc.ServiceDesc for BlockCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "containerd.services.blockcache.v1.BlockCache",
	HandlerType: (*BlockCacheServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Fill",
			Handler:       _BlockCache_Fill_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "services/blockcache/v1/blockcache.proto",
}
