// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: services/blockcache/v1/blockcache.proto
package blockcache

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type TTRPCBlockCacheService interface {
	Fill(context.Context, TTRPCBlockCache_FillServer) error
}

type TTRPCBlockCache_FillServer interface {
	Send(*FillMessage) error
	Recv() (*FillMessage, error)
	ttrpc.StreamServer
}

type ttrpcblockcacheFillServer struct {
	ttrpc.StreamServer
}

func (x *ttrpcblockcacheFillServer) Send(m *FillMessage) error {
	return x.StreamServer.SendMsg(m)
}

func (x *ttrpcblockcacheFillServer) Recv() (*FillMessage, error) {
	m := new(FillMessage)
	if err := x.StreamServer.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func RegisterTTRPCBlockCacheService(srv *ttrpc.Server, svc TTRPCBlockCacheService) {
	srv.RegisterService("containerd.services.blockcache.v1.BlockCache", &ttrpc.ServiceDesc{
		Streams: map[string]ttrpc.Stream{
			"Fill": {
				Handler: func(ctx context.Context, stream ttrpc.StreamServer) (interface{}, error) {
					return nil, svc.Fill(ctx, &ttrpcblockcacheFillServer{stream})
				},
				StreamingClient: true,
				StreamingServer: true,
			},
		},
	})
}

type TTRPCBlockCacheClient interface {
	Fill(context.Context) (TTRPCBlockCache_FillClient, error)
}

type ttrpcblockcacheClient struct {
	client *ttrpc.Client
}

func NewTTRPCBlockCacheClient(client *ttrpc.Client) TTRPCBlockCacheClient {
	return &ttrpcblockcacheClient{
		client: client,
	}
}

func (c *ttrpcblockcacheClient) Fill(ctx context.Context) (TTRPCBlockCache_FillClient, error) {
	stream, err := c.client.NewStream(ctx, &ttrpc.StreamDesc{
		StreamingClient: true,
		StreamingServer: true,
	}, "containerd.services.blockcache.v1.BlockCache", "Fill", nil)
	if err != nil {
		return nil, err
	}
	x := &ttrpcblockcacheFillClient{stream}
	return x, nil
}

type TTRPCBlockCache_FillClient interface {
	Send(*FillMessage) error
	Recv() (*FillMessage, error)
	ttrpc.ClientStream
}

type ttrpcblockcacheFillClient struct {
	ttrpc.ClientStream
}

func (x *ttrpcblockcacheFillClient) Send(m *FillMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ttrpcblockcacheFillClient) Recv() (*FillMessage, error) {
	m := new(FillMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}
