# commit to be tagged for new release
commit = "HEAD"

project_name = "containerd"
github_repo = "containerd/containerd"
match_deps = "^github.com/(containerd/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.4.0"

pre_release = true

preface = """\
This is an alpha release for the sixth major release of containerd. This release
contains significant refactoring to the underlying codebase which makes CRI
a first class plugin within containerd's core."""

# notable prs to include in the release notes, 1234 is the pr number
[notes]

[breaking]
